name: hyperion
version: '0.1.0.10'
author: David Simmons-Duffin
maintainer: davidsd@gmail.com
license: MIT
language: GHC2021

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -O2 -Wunused-packages

flags:
  use-external-hostname:
    default: false
    manual: true

library:
  source-dirs: src
  when:
    - condition: (flag(use-external-hostname))
      cpp-options: -DUSE_EXTERNAL_HOSTNAME
  dependencies:
    - base
    - process
    - time
    - random
    - filepath
    - attoparsec
    - bytestring
    - mtl
    - text
    - distributed-static
    - distributed-process
    - distributed-process-async
    - network-transport
    - network-transport-tcp
    - network
    - network-bsd
    - network-info
    - unix
    - binary
    - transformers
    - stm
    - directory
    - aeson
    - containers
    - pretty-show
    - pretty
    - exceptions
    - lens
    - extra
    - concurrent-output
    - shell-escape
    - rank1dynamic
    - sqlite-simple
    - resource-pool
    - transformers-base
    - optparse-applicative
    - servant-server
    - wai
    - warp
    - mime-mail
    - binaryhash
    - async
    - constraints
    - hyperion-static
    - vector
    - rusage

executables:
  example-hello-world:
    source-dirs: example/src-hello-world
    main: Main.hs
    dependencies:
      - base
      - hyperion
      - optparse-applicative
      - text
    ghc-options : -threaded

  example-lock-map:
    source-dirs: example/src-lock-map
    main: Main.hs
    dependencies:
      - base
      - hyperion
      - optparse-applicative
      - distributed-process
      - mtl
      - text
    ghc-options : -threaded

  example-polymorphic-remote:
    source-dirs: example/src-polymorphic-remote
    main: Main.hs
    dependencies:
      - base
      - hyperion
      - text
      - binary
      - containers
      - hyperion-static
    ghc-options : -threaded

  example-root-search:
    source-dirs: example/src-root-search
    main: Main.hs
    dependencies:
      - base
      - hyperion
      - optparse-applicative
      - filepath
      - mtl
    ghc-options : -threaded
