flags: {}
packages:
- '.'
extra-deps:
resolver: github:pkravchuk/hyperionage:snapshots/hyp-1.3.8.yaml
build:
  haddock-arguments:
    haddock-args:
    - "--odir=./docs"
    - "--hyperlinked-source"
  haddock-deps: false
arch: x86_64
